#! /bin/sh

###---AUTOSTART---###

nm-applet &
compton -b &
nitrogen --set-scaled --restore --head=0 &
nitrogen --set-scaled --restore --head=1 &
killall cleanfullscreen
cleanfullscreen &
launchpolybar &

###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

###---Global Settings---###
bspc config automatic_scheme spiral
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

bspc config split_ratio			 0.52
bspc config boderless_monocle	 true
bspc config gapless_monocle		 true

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above








